name = "qoi"
description = "Ada/SPARK implementation of the Quite Ok Image format"
version = "0.1.0"
licenses = "MIT"

authors = ["Fabien Chouteau", "Joffrey Huguet"]
maintainers= ["Fabien-Chouteau <chouteau@adacore.com>", "Joffrey Huguet <huguet@adacore.com>"]
maintainers-logins = ["Fabien-Chouteau", "joffreyhuguet"]
website = "https://github.com/Fabien-Chouteau/qoi-spark"
tags = ["image", "encoding", "qoi"]

[[depends-on]]
gnat = ">=11.2"
