

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: alire-project/setup-alire@v1
        with:
          toolchain: gprbuild gnat_native --disable-assistant
      - run: alr build
      - run: cd tests && alr build && ./bin/tests test.png encode.qoi && ./bin/tests encode.qoi decode.png
